### ISSUE TITLE
big(?) quickplot figures not displaying

### ISSUE THREAD

**Issue by svdavid** [LBHB/nems_web-PRE-4-28-2018#4]
console reports file not found, but file does exist. too big? tends to happen for tall figures with many subpanels. eg:
```[nems.uri WARNING] Couldn't read file at /auto/data/nems_db/results/259/sti034a-a1/env100.dlogn2_stpn2_fir2x15_lvl1_dexp1.fit_basic.2018-04-12T23:17:23/figure.0000.png
```

**Comment by jacobpennington** [comment]
Fixed, was an issue with pandas.to_html truncating modelname strings after 50 characters.
